from pathlib import Path
from typing import Any

import pandas as pd


REGISTRY_COLUMNS = [
    "factor_family",
    "factor_name",
    "source_name",
    "source_type",
    "expected_raw_fields",
    "possible_engineered_features",
    "update_frequency",
    "lag_requirement",
    "cost_level",
    "access_method",
    "requires_token",
    "suitable_for_training",
    "leakage_risk",
    "expected_predictive_value",
    "implementation_priority",
    "notes",
]


def _entry(
    factor_family: str,
    factor_name: str,
    source_name: str,
    source_type: str,
    expected_raw_fields: list[str],
    possible_engineered_features: list[str],
    update_frequency: str,
    lag_requirement: str,
    cost_level: str,
    access_method: str,
    requires_token: bool,
    suitable_for_training: bool,
    leakage_risk: str,
    expected_predictive_value: str,
    implementation_priority: str,
    notes: str,
) -> dict[str, Any]:
    return {
        "factor_family": factor_family,
        "factor_name": factor_name,
        "source_name": source_name,
        "source_type": source_type,
        "expected_raw_fields": expected_raw_fields,
        "possible_engineered_features": possible_engineered_features,
        "update_frequency": update_frequency,
        "lag_requirement": lag_requirement,
        "cost_level": cost_level,
        "access_method": access_method,
        "requires_token": requires_token,
        "suitable_for_training": suitable_for_training,
        "leakage_risk": leakage_risk,
        "expected_predictive_value": expected_predictive_value,
        "implementation_priority": implementation_priority,
        "notes": notes,
    }


FEATURE_SOURCE_REGISTRY = [
    _entry(
        "price_action",
        "ohlcv_return_momentum",
        "OHLCV daily bars",
        "market_data",
        ["date", "open", "high", "low", "close", "pre_close"],
        [
            "close/open/high/low returns",
            "return_1d",
            "return_5d",
            "return_20d",
            "return_60d",
            "gap return",
            "intraday reversal",
            "breakout from rolling high",
            "distance from MA5/MA20/MA60/MA120/MA250",
            "trend slope",
            "momentum acceleration",
        ],
        "daily",
        "Use only current and past prices. Do not use future close or label windows.",
        "free",
        "csv",
        False,
        True,
        "low",
        "medium",
        "P0",
        "Already partly implemented through OHLCV factor datasets; extend with longer trend and slope features.",
    ),
    _entry(
        "volume_liquidity",
        "volume_turnover_liquidity",
        "Exchange daily trading data",
        "market_data",
        ["volume", "turnover", "amount", "free_float_shares"],
        [
            "volume",
            "turnover",
            "amount",
            "dollar volume",
            "volume change",
            "turnover rate",
            "free-float turnover",
            "liquidity dry-up",
            "abnormal volume",
            "volume-price divergence",
        ],
        "daily",
        "Use same-day or delayed fields available before prediction time; lag free-float updates when sourced from fundamentals.",
        "free",
        "csv",
        False,
        True,
        "medium",
        "medium",
        "P0",
        "Liquidity features are useful for tradability and model stability, but vendor field timing must be checked.",
    ),
    _entry(
        "volatility_risk",
        "rolling_volatility_and_tail_risk",
        "OHLCV daily bars plus index returns",
        "market_data",
        ["high", "low", "close", "index_close", "risk_free_rate"],
        [
            "volatility_5d/20d/60d",
            "max drawdown",
            "downside volatility",
            "ATR",
            "high-low range",
            "beta to index",
            "idiosyncratic volatility",
            "crash risk",
            "tail risk",
        ],
        "daily",
        "Rolling risk metrics must use trailing windows only. Index beta needs aligned historical index returns.",
        "free",
        "csv",
        False,
        True,
        "low",
        "medium",
        "P0",
        "Risk features can help avoid unstable stocks and regime-specific false positives.",
    ),
    _entry(
        "valuation",
        "valuation_level_and_spread",
        "Public valuation datasets",
        "fundamental_data",
        ["pe_ttm", "pe_static", "pe_dynamic", "pb", "ps", "pcf", "ev_ebitda", "market_cap"],
        [
            "PE TTM",
            "PE static",
            "PE forward/dynamic",
            "PB",
            "PS",
            "PCF",
            "EV/EBITDA",
            "dividend yield",
            "PEG",
            "market cap",
            "free-float market cap",
            "valuation percentile vs own history",
            "valuation percentile vs industry",
            "valuation spread vs HS300/CSI500",
            "PE-to-growth match",
            "PB-to-ROE match",
            "valuation expansion/contraction trend",
        ],
        "daily/monthly",
        "Use the latest valuation snapshot known at or before the feature date; lag derived financial statement fields.",
        "free",
        "csv",
        False,
        True,
        "medium",
        "high",
        "P1",
        "Valuation should not be only PE. Cross-sectional and own-history percentiles are often more useful.",
    ),
    _entry(
        "fundamentals_profitability",
        "profitability_and_quality",
        "Financial statements and forecasts",
        "fundamental_data",
        ["revenue", "net_profit", "gross_margin", "operating_margin", "roe", "roa", "eps"],
        [
            "revenue",
            "net profit",
            "gross margin",
            "operating margin",
            "net margin",
            "ROE",
            "ROA",
            "ROIC",
            "EPS",
            "profit quality",
            "earnings surprise",
            "analyst forecast revision if available",
        ],
        "quarterly",
        "Lag by report publication date, not fiscal period end date. Forecast revisions require vendor timestamp checks.",
        "medium",
        "csv",
        True,
        True,
        "high",
        "high",
        "P1",
        "Publication-date lagging is mandatory because fiscal period labels can leak future reports.",
    ),
    _entry(
        "fundamentals_growth",
        "growth_rate_and_acceleration",
        "Financial statements",
        "fundamental_data",
        ["revenue", "net_profit", "eps", "operating_cash_flow", "book_value"],
        [
            "revenue growth YoY/QoQ",
            "net profit growth YoY/QoQ",
            "EPS growth",
            "operating cash flow growth",
            "book value growth",
            "sustainable growth rate",
            "acceleration/deceleration of growth",
        ],
        "quarterly",
        "Use only statements announced before the prediction date; restatements need point-in-time handling.",
        "free",
        "csv",
        False,
        True,
        "high",
        "medium",
        "P1",
        "Growth factors are useful only when calculated from properly lagged statements.",
    ),
    _entry(
        "balance_sheet_quality",
        "balance_sheet_risk_quality",
        "Financial statements",
        "fundamental_data",
        ["total_liabilities", "total_assets", "current_assets", "current_liabilities", "goodwill", "inventory", "receivables"],
        [
            "debt ratio",
            "current ratio",
            "quick ratio",
            "interest coverage",
            "goodwill ratio",
            "inventory growth",
            "receivable growth",
            "asset impairment risk",
            "leverage change",
        ],
        "quarterly",
        "Lag by announcement date and avoid using restated data that was unavailable at the prediction date.",
        "free",
        "csv",
        False,
        True,
        "high",
        "medium",
        "P2",
        "Quality factors may reduce blow-up risk but are slower moving than price and flow features.",
    ),
    _entry(
        "cash_flow_quality",
        "cash_flow_strength",
        "Cash flow statements",
        "fundamental_data",
        ["operating_cash_flow", "free_cash_flow", "net_profit", "capex", "cash_dividend"],
        [
            "operating cash flow",
            "free cash flow",
            "operating cash flow / net profit",
            "capex",
            "cash conversion ratio",
            "cash flow stability",
            "dividend coverage by cash flow",
        ],
        "quarterly",
        "Use report announcement dates. Avoid filling future quarterly reports backward.",
        "free",
        "csv",
        False,
        True,
        "high",
        "medium",
        "P2",
        "Cash-flow quality helps distinguish accounting profit from cash-backed profit.",
    ),
    _entry(
        "dividend_shareholder_return",
        "dividend_and_buyback_return",
        "Dividend plans and corporate actions",
        "corporate_action_data",
        ["cash_dividend", "payout_ratio", "ex_dividend_date", "buyback_amount"],
        [
            "cash dividend",
            "dividend yield",
            "payout ratio",
            "dividend stability",
            "buyback if available",
            "shareholder return score",
            "real dividend yield adjusted by price and payout sustainability",
        ],
        "event/annual",
        "Use announcement date and ex-dividend date correctly. Do not use future approved payouts before announcement.",
        "low",
        "csv",
        False,
        True,
        "medium",
        "medium",
        "P2",
        "Dividend features need sustainability checks; raw high yield can reflect price collapse.",
    ),
    _entry(
        "fund_holdings",
        "public_fund_ownership",
        "Fund reports and holdings disclosures",
        "institutional_holding_data",
        ["fund_code", "holding_shares", "holding_ratio", "report_date", "disclosure_date", "fund_type"],
        [
            "public fund holdings",
            "active fund holdings",
            "passive fund holdings",
            "ETF holdings",
            "holding ratio",
            "holding change",
            "concentration by fund type",
            "new fund entry",
            "fund crowding risk",
        ],
        "quarterly",
        "Use disclosure date, not report date, to avoid future holdings leakage.",
        "medium",
        "api",
        True,
        True,
        "high",
        "high",
        "P2",
        "Institutional holding data can be valuable but delayed and leakage-prone.",
    ),
    _entry(
        "foreign_institutional_flow",
        "northbound_foreign_flow",
        "Northbound capital and foreign holding data",
        "flow_data",
        ["northbound_net_buy", "foreign_holding_ratio", "holding_change", "ranking"],
        [
            "northbound capital flow",
            "foreign holding ratio",
            "super foreign holding ratio",
            "foreign holding change",
            "foreign ownership percentile",
            "foreign inflow acceleration",
            "top foreign holding ranking",
        ],
        "daily",
        "Use data timestamped before the prediction decision. Intraday availability differs by source.",
        "low",
        "api",
        False,
        True,
        "medium",
        "high",
        "P1",
        "Foreign flow may capture institutional preference, but source coverage and timing must be documented.",
    ),
    _entry(
        "stabilization_or_policy_funds",
        "state_backed_capital_proxy",
        "Public disclosures and policy proxies",
        "institutional_holding_data",
        ["holder_name", "holding_ratio", "holding_change", "report_date", "policy_event"],
        [
            "super stabilization fund holding ratio",
            "stabilization fund holding change",
            "stabilization fund ranking",
            "policy support signal",
            "state-backed capital proxy",
        ],
        "quarterly/event",
        "Treat holdings as known only after disclosure. Policy signals need explicit event timestamps.",
        "unknown",
        "future",
        False,
        False,
        "high",
        "unknown",
        "P3",
        "Keep as future research until source definitions are auditable and point-in-time.",
    ),
    _entry(
        "capital_flow_money",
        "money_flow_by_order_size",
        "Exchange/vendor money-flow data",
        "flow_data",
        ["main_net_inflow", "large_order_inflow", "small_order_inflow", "institutional_net_buy", "retail_net_buy"],
        [
            "main net inflow",
            "large order inflow",
            "small order inflow",
            "institutional net buy",
            "retail net buy",
            "money flow divergence",
            "fund flow persistence",
        ],
        "daily/intraday",
        "Use end-of-day flow only after market close; intraday experiments need strict timestamp alignment.",
        "low",
        "api",
        False,
        True,
        "medium",
        "medium",
        "P1",
        "Flow definitions vary by vendor, so engineered features should record source and calculation method.",
    ),
    _entry(
        "chip_cost_distribution",
        "cost_distribution_pressure_support",
        "Broker terminal or vendor chip distribution",
        "alternative_data",
        ["cost_distribution", "winner_ratio", "average_holding_cost", "cost_concentration"],
        [
            "cost concentration",
            "winner ratio",
            "average holding cost",
            "90% cost concentration",
            "chip lock-up",
            "pressure level",
            "support level",
            "profit-taking pressure",
        ],
        "daily",
        "Only use data snapshots available at prediction time. Vendor formulas may be opaque.",
        "high",
        "broker_terminal",
        True,
        False,
        "medium",
        "unknown",
        "P3",
        "Potentially useful but not yet suitable for default training because source and formula reproducibility are uncertain.",
    ),
    _entry(
        "industry_style_factors",
        "industry_and_style_relative_strength",
        "Industry classification and cross-sectional factor data",
        "classification_data",
        ["industry_code", "industry_name", "style_exposure", "industry_index_close", "industry_fund_flow"],
        [
            "industry classification",
            "industry momentum",
            "industry valuation percentile",
            "industry capital flow",
            "industry earnings trend",
            "style factor: value/growth/quality/momentum/low-volatility/high-dividend/small-cap/large-cap",
            "relative strength vs industry",
        ],
        "daily/monthly",
        "Use historical classifications and avoid applying current industry membership backward.",
        "low",
        "csv",
        False,
        True,
        "medium",
        "high",
        "P1",
        "Relative features can help separate stock-specific strength from industry beta.",
    ),
    _entry(
        "index_component_factors",
        "index_membership_and_rebalance",
        "Index constituent files",
        "index_data",
        ["index_code", "is_member", "index_weight", "rebalance_date", "component_rank"],
        [
            "CSI300/CSI500/CSI1000 membership",
            "index inclusion/exclusion",
            "index weight",
            "passive fund flow impact",
            "component ranking",
            "upcoming rebalance risk",
        ],
        "monthly/event",
        "Use only announced constituent changes. Do not use future rebalance membership before announcement.",
        "low",
        "csv",
        False,
        True,
        "medium",
        "medium",
        "P2",
        "Index membership can affect liquidity and passive flow but needs event-date precision.",
    ),
    _entry(
        "macro_policy",
        "macro_liquidity_policy_regime",
        "Public macroeconomic and policy data",
        "macro_data",
        ["interest_rate", "bond_yield", "credit_spread", "rmb_fx", "commodity_price", "cpi", "ppi", "pmi"],
        [
            "interest rates",
            "bond yield",
            "credit spread",
            "RMB exchange rate",
            "commodity prices",
            "CPI/PPI",
            "PMI",
            "liquidity indicators",
            "policy announcements",
            "sector policy support",
        ],
        "daily/monthly/event",
        "Use release dates, not economic period labels. Macro releases often have publication lag.",
        "free",
        "api",
        False,
        True,
        "high",
        "medium",
        "P2",
        "Macro factors are useful for regime context but can be too broad for single-stock labels.",
    ),
    _entry(
        "sentiment_news_event",
        "news_announcement_event_sentiment",
        "News, announcements, social media, and research reports",
        "text_event_data",
        ["news_time", "announcement_time", "sentiment_score", "event_type", "source"],
        [
            "news sentiment",
            "announcement sentiment",
            "social media heat",
            "analyst report sentiment",
            "earnings announcement",
            "dividend announcement",
            "M&A",
            "litigation/regulatory penalty",
            "management change",
            "product/event catalyst",
        ],
        "intraday/event",
        "Timestamp every text item. Do not use articles, reports, or announcements published after the prediction time.",
        "high",
        "web",
        True,
        False,
        "high",
        "unknown",
        "P3",
        "Text features need robust timestamping and source rights before they are used in training.",
    ),
    _entry(
        "market_regime_timing",
        "market_breadth_and_regime",
        "Index, breadth, margin, and market statistics",
        "market_data",
        ["index_close", "advance_count", "decline_count", "limit_up_count", "limit_down_count", "margin_balance"],
        [
            "index trend",
            "market breadth",
            "up/down ratio",
            "limit-up/limit-down count",
            "margin financing balance",
            "market volatility regime",
            "bull/bear/sideways regime",
            "risk-on/risk-off signal",
        ],
        "daily",
        "Use market-wide features known by the decision time. Regime labels must be calculated from past data only.",
        "free",
        "csv",
        False,
        True,
        "medium",
        "high",
        "P1",
        "Regime features help explain why the same stock factors work in some periods and fail in others.",
    ),
    _entry(
        "custom_ai_factors",
        "composite_ai_research_scores",
        "Future internal factor engine",
        "derived_factor",
        ["component_scores", "feature_version", "calculation_time"],
        [
            "bottom-fishing index",
            "institutional control score",
            "super foreign overview score",
            "public fund ranking score",
            "stabilization fund ranking score",
            "valuation safety score",
            "multi-factor confidence score",
            "regime-adjusted signal score",
        ],
        "daily/future",
        "Composite scores must be built only from lag-safe inputs and versioned to avoid hidden leakage.",
        "unknown",
        "future",
        False,
        False,
        "high",
        "unknown",
        "P3",
        "Placeholder for future derived scores. Do not train on these until every component source is auditable.",
    ),
]


def _copy_records(records: list[dict[str, Any]]) -> list[dict[str, Any]]:
    return [record.copy() for record in records]


def get_all_features() -> list[dict[str, Any]]:
    return _copy_records(FEATURE_SOURCE_REGISTRY)


def get_features_by_family(factor_family: str) -> list[dict[str, Any]]:
    family = factor_family.strip().lower()
    return [
        record.copy()
        for record in FEATURE_SOURCE_REGISTRY
        if record["factor_family"].lower() == family
    ]


def get_training_ready_features() -> list[dict[str, Any]]:
    return [
        record.copy()
        for record in FEATURE_SOURCE_REGISTRY
        if record["suitable_for_training"]
    ]


def get_high_priority_features() -> list[dict[str, Any]]:
    return [
        record.copy()
        for record in FEATURE_SOURCE_REGISTRY
        if record["implementation_priority"] in {"P0", "P1"}
    ]


def get_high_leakage_risk_features() -> list[dict[str, Any]]:
    return [
        record.copy()
        for record in FEATURE_SOURCE_REGISTRY
        if record["leakage_risk"] == "high"
    ]


def get_token_required_features() -> list[dict[str, Any]]:
    return [
        record.copy()
        for record in FEATURE_SOURCE_REGISTRY
        if record["requires_token"]
    ]


def registry_to_dataframe(records: list[dict[str, Any]] | None = None) -> pd.DataFrame:
    data = get_all_features() if records is None else _copy_records(records)
    display_rows = []
    for record in data:
        row = record.copy()
        for field in ["expected_raw_fields", "possible_engineered_features"]:
            row[field] = " | ".join(row[field])
        display_rows.append(row)
    return pd.DataFrame(display_rows, columns=REGISTRY_COLUMNS)


def export_registry_to_csv(output_path: str | Path) -> Path:
    path = Path(output_path)
    path.parent.mkdir(parents=True, exist_ok=True)
    registry_to_dataframe().to_csv(path, index=False, encoding="utf-8-sig")
    return path


def summarize_factor_families() -> pd.DataFrame:
    df = registry_to_dataframe()
    if df.empty:
        return pd.DataFrame()
    summary = (
        df.groupby("factor_family", dropna=False)
        .agg(
            feature_count=("factor_name", "count"),
            training_ready_count=("suitable_for_training", "sum"),
            token_required_count=("requires_token", "sum"),
            highest_priority=("implementation_priority", "min"),
            highest_leakage_risk=("leakage_risk", lambda values: "high" if "high" in set(values) else ("medium" if "medium" in set(values) else "low")),
        )
        .reset_index()
        .sort_values(["highest_priority", "factor_family"])
    )
    return summary
